version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Evita sobrescrever os módulos do container
    ports:
      - "4200:4200"
      - "49153:49153"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Garante que o Angular detecte mudanças nos arquivos

  db:
    image: mysql:8.0.36
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Senha do root do MySQL
      MYSQL_DATABASE: denarius  # Nome do banco de dados
    ports:
      - "3307:3306"  # Porta para acessar o MySQL
    volumes:
      - db_data:/var/lib/mysql  # Persistência dos dados do banco

  backend:
    build:
      context: ./backend  # Caminho para o diretório do backend
      dockerfile: Dockerfile  # Nome do arquivo Dockerfile
    volumes:
      - ./backend:/app  # Monta o código para permitir hot reload
    ports:
      - "8000:8000"  # Expondo a porta 8000 para o FastAPI
    depends_on:
      - db  # Garante que o MySQL inicie antes do backend
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=denarius
    entrypoint: ["/app/wait-for-db.sh"]  # Executa o script antes do backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app  # Força o reload ao detectar mudanças

volumes:
  db_data:  # Volume para persistência do MySQL
